/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

/**
 *
 * @author Ahmed
 */
public class MenuUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuUI
     */
    public MenuUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentbtn = new javax.swing.JButton();
        departmentbtn = new javax.swing.JButton();
        coursebtn = new javax.swing.JButton();
        studentcoursebtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo of app.png"))); // NOI18N

        studentbtn.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        studentbtn.setForeground(new java.awt.Color(255, 153, 0));
        studentbtn.setText("STUDENT MANAGER\n");
        studentbtn.setAlignmentY(0.0F);
        studentbtn.setMargin(null);
        studentbtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        studentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentbtnActionPerformed(evt);
            }
        });

        departmentbtn.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        departmentbtn.setForeground(new java.awt.Color(255, 153, 0));
        departmentbtn.setText("DEPARTMENT MANAGER\n");
        departmentbtn.setAlignmentY(0.0F);
        departmentbtn.setMargin(null);
        departmentbtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        departmentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentbtnActionPerformed(evt);
            }
        });

        coursebtn.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        coursebtn.setForeground(new java.awt.Color(255, 153, 0));
        coursebtn.setText("COURSE MANAGER\n");
        coursebtn.setAlignmentY(0.0F);
        coursebtn.setMargin(null);
        coursebtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        coursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursebtnActionPerformed(evt);
            }
        });

        studentcoursebtn.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        studentcoursebtn.setForeground(new java.awt.Color(255, 153, 0));
        studentcoursebtn.setText("STUDENT COURSE MANAGER\n");
        studentcoursebtn.setAlignmentY(0.0F);
        studentcoursebtn.setMargin(null);
        studentcoursebtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        studentcoursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentcoursebtnActionPerformed(evt);
            }
        });

        logoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        logoutbtn.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("Log out");
        logoutbtn.setAlignmentY(0.0F);
        logoutbtn.setMargin(null);
        logoutbtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coursebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentcoursebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(studentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(departmentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentcoursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentbtnActionPerformed
        // TODO add your handling code here:
        StudentUI studentui = new StudentUI();
        studentui.show();
        dispose();
    }//GEN-LAST:event_studentbtnActionPerformed

    private void departmentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentbtnActionPerformed
        // TODO add your handling code here:
        DepartmentUI departmentui = new DepartmentUI();
        departmentui.show();
        dispose();
    }//GEN-LAST:event_departmentbtnActionPerformed

    private void coursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursebtnActionPerformed
        // TODO add your handling code here:
        CourseUI courseui = new CourseUI();
        courseui.show();
        dispose();
    }//GEN-LAST:event_coursebtnActionPerformed

    private void studentcoursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentcoursebtnActionPerformed
        // TODO add your handling code here:
        StudentCourseUI studentcourseui = new StudentCourseUI();
        studentcourseui.show();
        dispose();
    }//GEN-LAST:event_studentcoursebtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        LoginUI loginui = new LoginUI();
        loginui.show();
        dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coursebtn;
    private javax.swing.JButton departmentbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton studentbtn;
    private javax.swing.JButton studentcoursebtn;
    // End of variables declaration//GEN-END:variables
}
